// services/api/src/services/paystubPdf.service.js
const PDFDocument = require('pdfkit');

/**
 * paystub: wo payload jo payrollAuto.service.js me bana rahe ho
 * (name, periodStart, periodEnd, payDate, gross, net, etc.)
 */
function buildPaystubPdfBuffer(paystub) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40 });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const {
        name,
        email,
        address,
        state,
        periodStart,
        periodEnd,
        payDate,
        gross,
        deductions,
        net,
        federal,
        stateTax,
        ss,
        medicare,
        ytdGross,
        ytdDeductions,
        ytdNet,
      } = paystub;

      // Header
      doc.fontSize(20).text('🏠 PropertySanta Paystub', { align: 'left' });
      doc.moveDown(0.5);
      doc.fontSize(10).text(`Pay Date: ${payDate}`, { align: 'right' });
      doc.moveDown();

      // Employee Info
      doc.fontSize(12).font('Helvetica-Bold').text('Employee Info');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10);
      doc.text(`Name: ${name || ''}`);
      if (email) doc.text(`Email: ${email}`);
      if (address) doc.text(`Address: ${address}`);
      if (state) doc.text(`State: ${state}`);
      doc.moveDown();

      // Period
      doc.fontSize(12).font('Helvetica-Bold').text('Pay Period');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10);
      doc.text(`Start: ${periodStart}`);
      doc.text(`End:   ${periodEnd}`);
      doc.moveDown();

      // Earnings
      doc.fontSize(12).font('Helvetica-Bold').text('Earnings');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10);
      doc.text(`Gross Pay: $${Number(gross || 0).toFixed(2)}`);
      doc.moveDown();

      // Deductions
      doc.fontSize(12).font('Helvetica-Bold').text('Deductions');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10);
      doc.text(`Federal:   $${Number(federal || 0).toFixed(2)}`);
      doc.text(`State:     $${Number(stateTax || 0).toFixed(2)}`);
      doc.text(`Social Security: $${Number(ss || 0).toFixed(2)}`);
      doc.text(`Medicare:  $${Number(medicare || 0).toFixed(2)}`);
      doc.text(`Total Deductions: $${Number(deductions || 0).toFixed(2)}`);
      doc.moveDown();

      // Net Pay
      doc.fontSize(12).font('Helvetica-Bold').text('Net Pay');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(11);
      doc.text(`Net Pay: $${Number(net || 0).toFixed(2)}`);
      doc.moveDown();

      // YTD
      doc.fontSize(12).font('Helvetica-Bold').text('Year-to-Date');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10);
      doc.text(`YTD Gross:       $${Number(ytdGross || 0).toFixed(2)}`);
      doc.text(`YTD Deductions:  $${Number(ytdDeductions || 0).toFixed(2)}`);
      doc.text(`YTD Net:         $${Number(ytdNet || 0).toFixed(2)}`);

      doc.moveDown(2);
      doc.fontSize(8).fillColor('#777')
        .text('This paystub is auto-generated by PropertySanta Payroll.', { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { buildPaystubPdfBuffer };
